### PR TITLE
fix: tab completion

### PR DESCRIPTION
**Pull request by LazyGon**
- This usage of tabcomplete event breaks other plugin's tabcompletion.
- Used TabExecutor.

### CODE REVIEW

**Comment by LazyGon** [comment]
Not all plugin commands will receive player name as the first argument.

**Comment by RDProjectOfficial** [comment]
Hi. Okay wait fixing :)

**Comment by RDProjectOfficial** [comment]
i will recode plugin with 0 ;)

**Comment by LazyGon** [comment]
Sorry, I mistakenly force pushed to forked repository.
I will create PR again.

**Comment by LazyGon** [comment]
Ah, "with 0" means you do this by your self and I do not need create new PR maybe?
If your rewritten code has same problem, I will create new PR :wave:

**Pull request closed without merging**
